DROP DATABASE IF EXISTS NumberGameDB;

CREATE DATABASE NumberGameDB;

USE NumberGameDB;

CREATE TABLE Game (
	GameId INT AUTO_INCREMENT PRIMARY KEY,
    ActualAnswer VARCHAR(4) NOT NULL,
    GameStatus VARCHAR(10) DEFAULT 'Incomplete' NOT NULL
);

CREATE TABLE Round (
	RoundNum INT AUTO_INCREMENT PRIMARY KEY,
    GameId INT NOT NULL,
    Guess VARCHAR(4) NOT NULL,
    RoundResult VARCHAR(10) DEFAULT 'e:0 p:0',
    RoundTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GameId)
		REFERENCES Game(GameId)
);

